name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Build wheel
        run: |
          python -m build -w

      - name: Run compile check
        run: |
          python -m compileall -q src

      - name: Run tests with coverage
        run: |
          PYTHONPATH=src python -m pytest --cov=src --cov-report=xml -q

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: dist-wheel
          path: dist/*.whl

      - name: Lint (optional)
        run: |
          pip install flake8
          flake8 src || true
